### ISSUE TITLE
外接显示器不能用

### ISSUE THREAD

**Issue by yezedada** [Silence-dream/TX7-CT5DS-EFI#1]
你好，我的电脑别的问题都没有，就是外接显示屏不显示，怎么解决啊？用的minidp接口

**Comment by Silence-dream** [comment]
因为无法驱动 gtx1660ti 所以默认屏蔽了独显. 外接显示器走的是独显的输出,屏蔽了独显自然也就无法外接屏幕了

**Comment by Silence-dream** [comment]
> 你好，我的电脑别的问题都没有，就是外接显示屏不显示，怎么解决啊？用的minidp接口

因为无法驱动 gtx1660ti 所以默认屏蔽了独显. 外接显示器走的是独显的输出,屏蔽了独显自然也就无法外接屏幕了

**Comment by yezedada** [comment]
这个电脑中间的那个minidp口是核显输出，应该可以显示🤔

**Comment by Silence-dream** [comment]
> 这个电脑中间的那个minidp口是核显输出，应该可以显示🤔

这就不清楚了,我没有显示器测试
